### ISSUE TITLE
how it work?

### ISSUE THREAD

**Issue by foxhacker0000** [viraj-bookanna/MEGA-stream#1]
how can i use it?

i cloned it and installed requestment.txt file success in linux ubuntu 22.04
but cannot use it please make document for project

**Comment by viraj-bookanna** [comment]
U can run it with just "flask run" command in cloned directory. You may have to rename app_flask.py to app.py

**Comment by viraj-bookanna** [comment]
> how can i use it?
> 
> i cloned it and installed requestment.txt file success in linux ubuntu 22.04 but cannot use it please make document for project

And also same with other one. You need only one file of them.
Other file is serving via aiohttp web. If you want your server async. You can use that file

**Comment by Rocket3192** [comment]
Hi, not working for me :
![image](https://github.com/viraj-bookanna/MEGA-stream/assets/123319690/da9bb90e-d74f-4dc7-9393-6c2beb8d8548)
![image](https://github.com/viraj-bookanna/MEGA-stream/assets/123319690/04f17631-aff6-4565-b7ca-5297fadddc45)
Tried with app.py, and the flask one, and tried to rename flask to app.py

**Comment by Rocket3192** [comment]
Hi, doesn't work for me, 404 not found, where to put the link ? 
Could you explain ? Because there is about nothing to read in the readme

**Comment by viraj-bookanna** [comment]
> Hi, doesn't work for me, 404 not found, where to put the link ? Could you explain ? Because there is about nothing to read in the readme

Well, i think you haven't looked at the code
The download page is on http://your_host:port/download

**Comment by Rocket3192** [comment]
Alright, it's already better, it doesn't work for folders though, even when using a specific file link inside that folder

"TypeError("'NoneType' object is not subscriptable")"
TS file btw

I found MegaDownloader yesterday, it's working for folders in 1.8
